services:
  frontend:
    build: ./frontend-flask
    container_name: tfg_frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build: ./backend-fastapi
    container_name: tfg_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./downloads:/data/downloaded_pdfs   # 👈 AQUÍ

  db:
    image: postgres:15
    container_name: tfg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tfg
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: tfg_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: